app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.ItemView.as_view(), name='item'),
    path('item/<int:pk>/item_edit/', views.Item_editView.as_view(), name='item_edit'),
    path('item/item_add', views.item_add, name='item_add'),
    path('item/item_del/<int:pk>/', views.Item_del, name='item_del'),
    path('item/<int:pk>/calendar/', views.ItemCalendar.as_view(), name='calendar'),
    path('item/<int:pk>/calendar/<int:year>/<int:month>/<int:day>/', views.ItemCalendar.as_view(), name='calendar'),
    path('item/<int:pk>/booking/<int:year>/<int:month>/<int:day>/<int:hour>/', views.Booking.as_view(), name='booking'),   
    path('item/<int:pk>/bookkk/<int:year>/<int:month>/<int:day>/<int:hour>/', views.bookkk, name='bookkk'), 
    path('item/<int:pk>/myschedule_detail/<int:year>/<int:month>/<int:day>/<int:hour>/', views.MyScheduleDetail.as_view(), name='myschedule_detail'),   
    path('item/myschedule_del/<int:pk>/', views.myschedule_del, name='myschedule_del'), 
    path('item/<int:pk>/rest/', views.Rest.as_view(), name='rest'),   
    path('item/<int:pk>/sendrest/', views.sendrest, name='sendrest'), 
    path('calendar/<int:pk>/my_page_calendar/', views.MyPageCalendar.as_view(), name='my_page_calendar'),
    path('calendar/<int:pk>/my_page_calendar/<int:year>/<int:month>/<int:day>/', views.MyPageCalendar.as_view(), name='my_page_calendar'),
    path('item/<int:pk>/config/<int:year>/<int:month>/<int:day>/', views.MyPageDayDetail.as_view(), name='my_page_day_detail'),#詳細
    path('item/holiday/add/<int:pk>/<int:year>/<int:month>/<int:day>/<int:hour>/', views.my_page_holiday_add_hour, name='my_page_holiday_add_hour'),
    path('item/holiday/add/<int:pk>/<int:year>/<int:month>/<int:day>/', views.my_page_holiday_add_day, name='my_page_holiday_add_day'),
    path('item/delete_hour/<int:pk>/<int:year>/<int:month>/<int:day>/<int:hour>/', views.Delete_hour, name='delete_hour'),
    path('item/delete_day/<int:pk>/<int:year>/<int:month>/<int:day>/', views.Delete_day, name='delete_day'),
    path('item/eventcalendar/', views.EventcalendarView.as_view(), name='eventcalendar'),
    path('item/eventcalendar/<int:year>/<int:month>/', views.EventcalendarView.as_view(), name='eventcalendar'),
    path('item/event_add/', views.event_add, name='event_add'),
    path('item/some_event_add/', views.some_event_add, name='some_event_add'),
    path('item/event_del/<int:pk>/', views.event_del, name='event_del'),
    path('eventcalendar/<int:pk>/event_detail/', views.EventdetailView.as_view(), name='event_detail'),

    path('eventcalendar/<int:pk>/event_detail/event_edit/', views.Event_editView.as_view(), name='event_edit'),

    path('eventcalendar/<int:pk>/participant_add/', views.participant_add, name='participant_add'),
    path('eventcalendar/<int:pk>/<str:name>/participant_del/', views.participant_del, name='participant_del'),
    path('eventcalendar/<int:pk>/participant_detail/', views.ParticipantdetailView.as_view(), name='participant_detail'),
    path('eventcalendar/<int:pk>/my_participant_del/', views.my_participant_del, name='my_participant_del'),
]

app_name= 'app'

uncpj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include(('app.urls', 'pjhoge'), namespace='pjhoge')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app/booking.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="card eveadd-auth my-5 mx-auto">
    <div class="eveadd-body">
        <h5 class="card-title text-center">{{ item.name }}予約フォーム</h5>
        <p style="font-size: 16px;">{{ view.kwargs.year }}年{{ view.kwargs.month }}月{{ view.kwargs.day }}日 {{ view.kwargs.hour }}時から</p>
        <form action = "{% url 'app:bookkk' item.pk view.kwargs.year view.kwargs.month view.kwargs.day view.kwargs.hour %}" method="POST" class="form-auth" onSubmit="return disp_book()">
            {% csrf_token %}
            <div class="form-label-group form_wrap form_wrap-2">
                <input type="number" class='form-control' min="1" max = "72" value="1" name="number" placeholder='時間'><h5>時間</h5> 
            </div>
            <br>
            <br>
            <div class="form-label-group">
                {% render_field form.name class='form-control'  placeholder='名前' %}
            </div>
            <br>
            <p class="indent-2" style="font-size: 16px;">で予約する</p>
            <br>

            <div class="form-label-group form_wrap form_wrap-2">
                <h6>4桁以下の暗証番号 : </h6>
                <input type="text" id="pas" name="pw" maxlength="4" pattern="\d*" placeholder="暗証番号" oninput="value = value.replace(/[０-９]/g,s => String.fromCharCode(s.charCodeAt(0) - 65248)).replace(/\D/g,'');" >
                <p>※予約キャンセル時に必要になります。<br>必須ではありませんが自分での予約キャンセルができなくなります。</p>
            </div>
            <br>
            
            <div class="button mx-auto">
                <button class="btn btn-lg btn-primary btn-block mx-auto" type="submit">送信</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

app/templates/app/event_add.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div style="text-align: left;">
    <a href="{% url 'app:item' %}" class="btn btn-default"> << カレンダーへ戻る</a>
</div>
<br>
<a href="{% url 'app:some_event_add' %}" class="btn btn-outline-primary">まとめて追加したい場合</a>

<div class="card eveadd-auth my-5 mx-auto"> 
    <div class="eveadd-body">
        <h5 class="card-title text-center">受付追加フォーム</h5>
        <form method="post" class="form-auth" enctype="multipart/form-data">
            {% csrf_token %}

            <li type="disc" class="font-weight-bold" style="font-size: 13px; color: rgb(0, 102, 143);">イベント名</li><br>
            <div class="form-label-group">
                {% render_field form.name class='form-control' placeholder='イベント名' %}
            </div>
            <br><br>
            
            <li type="disc" class="font-weight-bold" style="font-size: 13px; color: rgb(0, 102, 143);">追加する期間の指定</li><br>
            <div class="form-label-group">
                <input class='form-control' type="date" name="date"  placeholder="イベント開催日" required>
            </div>
            
            <br><br>

            <li type="disc" class="font-weight-bold" style="font-size: 13px; color: rgb(0, 102, 143);">予約期限の指定</li>
            <p>　※開催 [ 1/5 ] 、許可 [ 2日前 ] 、締切 [ 1日前 ]の場合
                <br>　　　　　　→予約期間　[ 1/3　00:00 ] ～ [ 1/4　23:59 ] </p>
            <div class="form-label-group">
                {% render_field form.book_start class='form-control' min="0" placeholder='何日前に予約を許可するか' %}
                <p style="text-align: right;">日前に予約を許可</p>
            </div>   
            <div class="form-label-group">
                {% render_field form.book_end class='form-control' min="0" placeholder='何日前に締め切るか' %}
                <p style="text-align: right;">日前に予約を締切</p>
            </div>

            <br><br>

            <li type="disc" class="font-weight-bold" style="font-size: 13px; color: rgb(0, 102, 143);">予約制限人数</li>
            <p>　※未入力の場合は無制限になります</p>
            <div class="form-label-group">
                {% render_field form.limit class='form-control' placeholder='予約制限人数' %}
            </div>
            <br><br>


            <li type="disc" class="font-weight-bold" style="font-size: 13px; color: rgb(0, 102, 143);">備考</li><br>
            <div class="form-label-group">
                {% render_field form.description class='form-control' placeholder='備考' %}
            </div>
            <div class="button mx-auto">
                <button class="btn btn-lg btn-primary btn-block mx-auto" type="submit">受付を追加</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

app/templates/app/event_edit.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}
<br>
<a href="{% url 'app:item' %}"><< カレンダーへ戻る</a>

<div class="card eveadd-auth my-5 mx-auto">
    <div class="eveadd-body">
        <h5 class="card-title text-center">受付編集ページ</h5>
        <form method="post" class="form-auth" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form.as_p }}

            
                <div class="button mx-auto">
                    <button class="btn btn-lg btn-primary btn-block mx-auto" type="submit">保存</button>
                </div>
        </form>
    </div>
</div>

{% endblock %}

app/templates/app/item.html
{% extends 'app/base.html' %}

{% block content %}

<details>
    <summary style="color: rgb(96, 96, 248);">予約をキャンセルしたい場合</summary>
    <p class="indent-1-e">
        ⇒予約したページで自分の名前をクリックしてください。
        <br>また、暗証番号がわからなくなった場合はサークル責任者に連絡してキャンセルしてもらってください。
    </p>
</details>

<div class="text-center my-2 my-sm-5">
    <div class="mb-5">
        <h3>受付一覧</h3>
    </div>
    
    <h5>===潜り予約===</h5>
    <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-11">
            {% if user.is_authenticated %}
                <div style="text-align: left;">
                    <a href="{% url 'app:event_add' %}" class="btn btn-default">カレンダーに受付追加</a>
                </div>
            {% endif %}

            <div style="display: flex;">
                <div class="hako " style="background-color: rgb(237, 255, 223); color: rgb(100, 100, 100); font-weight:  bold;">
                    　予約期間　　
                </div>
                <div>　</div>
                <div class="hako" style="background-color: rgb(255, 229, 229); color: rgb(100, 100, 100); font-weight:  bold;">
                    　予約期間外　
                </div>
            </div>
        </div>
    </div>

    <iframe class="embed-responsive-item evecal" src="item/eventcalendar/"  frameborder="0">
    </iframe>
    


    <br><br>
    <h5>===車やその他受付===</h5>
    {% if user.is_authenticated %}
        <div style="text-align: left;">
            <a href="{% url 'app:item_add' %}" class="btn btn-default">受付枠追加</a>
        </div>
    {% endif %}
    <div class="row">
        {% for item in item_data %} 
            <div class="col-sm-6">
                <div class="card img-thumbnail itemlist mb-3">
                    <div class="card-body text-center px-2 py-2">       
                        <div style="text-align: left;">
                            {% if user.is_authenticated %}
                                <a href="{% url 'app:item_edit' item.pk %}" >編集ページへ</a>       
                            {% endif %}      
                        </div>
                                  
                        <h5 class="font-weight-bold">{{ item.name }} 受付</h5>
                        <br>
                        <div class="text-left">
                            <h6 style="text-align: left">備考:</h6>
                            <p class="indent-1">{{ item.description|linebreaksbr }}</p> 
                        </div>
                        <a href="{% url 'app:calendar' item.pk %}" class="btn btn-outline-primary" style="font-size: 13px;">予約へ</a>
                                      
                    </div>     
                </div>    
            </div>
                {% empty %}
                <div class="col-12">
                    <br>
                    <p style="font-size: 16px; text-align: center;">　　受付していません</p>
                </div>
                {% endfor %}
    </div>

    <br>
</div>


{% endblock %}

app/templates/app/item_add.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="card eveadd-auth my-5 mx-auto">
    <div class="eveadd-body">
        <h5 class="card-title text-center">{{ item.name }}受付追加フォーム</h5>
        <form method="post" class="form-auth" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-label-group form_wrap form_wrap-2">
                {% render_field form.name class='form-control' placeholder='受付表示名' %}
            </div>
            <div class="form-label-group">
                {% render_field form.description class='form-control' placeholder='備考' %}
            </div>
            <div class="button mx-auto">
                <button class="btn btn-lg btn-primary btn-block mx-auto" type="submit">受付を追加</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

app/templates/app/item_edit.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}
<br>
<a href="{% url 'app:item' %}"><< 一覧へ戻る</a>

<div class="card eveadd-auth my-5 mx-auto">
    <div class="eveadd-body">
        <h5 class="card-title text-center">受付編集ページ</h5>
        <form method="post" class="form-auth" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form.as_p }}

            
                <div class="button mx-auto">
                    <button class="btn btn-lg btn-primary btn-block mx-auto" type="submit">保存</button>
                </div>
        </form>
    </div>
</div>

{% endblock %}

app/templates/app/my_page_calendar.html
{% extends 'app/base.html' %}
<!--mypage_cal-->

{% block content %}

    <h4>スタッフ {{ item.name }}  受付カレンダー</h4>
    <p>{{ start_day }} - {{ end_day }}</p>
    <a href="{% url 'app:calendar' item.pk %}">閲覧用カレンダーページへ</a>
    <br><a href="{% url 'app:rest' item.pk %}">予約不可 一括設定へ</a>

    <div class="table-responsive">
        <table class="table table-bordered table-striped table-sm text-center bg-light">
                <tr>
                    <td><a href="{% url 'app:my_page_calendar' item.pk before.year before.month before.day %}" class="btn btn-warning">前週</a></th>
                    {% for day in days %}
                        {% if day in public_holidays %}
                            <th style="background-color: yellow">{{ day | date:"d(D)" }}
                        {% elif day.weekday == 5 %}
                            <th style="color: blue;">{{ day | date:"d(D)" }}
                        {% elif day.weekday == 6 %}
                            <th style="color: red;">{{ day | date:"d(D)" }}
                        {% else %}
                            <th>{{ day | date:"d(D)" }}
                        {% endif %}

                        <br><a href="{% url 'app:my_page_day_detail' item.pk day.year day.month day.day %}">詳細</a>
                    {% endfor %}
                    <td><a href="{% url 'app:my_page_calendar' item.pk next.year next.month next.day %}" class="btn btn-warning">次週</a></th>
                </tr>

            <tbody>
                {% for hour, schedules in calendar.items %}
                    <tr style="font-size:12px">
                        <td scope='row'>{{ hour }}:00</td>
                        {% for dt, book in schedules.items %}
                            <td>
                                {% if book %}

                                    {% for s in book %}
                                    <p class="font-weight-bold text-success" style="display:inline;">{{ s.name }}:</p>
                                    <form method="POST" style="display: inline" action="{% url 'app:delete_hour' item.pk dt.year dt.month dt.day hour%}">
                                        {% csrf_token %}
                                        <button class="btn btn-danger" type="submit">削除</button>
                                    </form>
                                    {% endfor %}
                                {% else %}
                                    <i class="far fa-circle text-info"></i>
                                {% endif %}
                            </td>

                        {% endfor %}
                        <td>
                            {{ hour }}:00
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
    </table>

    <form action="{% url 'app:item_del' item.pk %}" method="POST" onSubmit="return disp_item_del()">
        {% csrf_token %}
        <button class="btn btn-warning" type="submit">受付を消去する</button>
    </form>
    <br>
{% endblock %}

app/templates/app/my_page_calender.html
{% extends 'app/base.html' %}
<!--mypage_cal-->

{% block content %}

    <h4>スタッフ {{ item.name }}  受付カレンダー</h4>
    <p>{{ start_day }} - {{ end_day }}</p>
    <a href="{% url 'app:calendar' item.pk %}">閲覧用カレンダーページへ</a>
    <br><a href="{% url 'app:rest' item.pk %}">予約不可 一括設定へ</a>

    <div class="table-responsive">
        <table class="table table-bordered table-striped table-sm text-center bg-light">
                <tr>
                    <td><a href="{% url 'app:my_page_calendar' item.pk before.year before.month before.day %}" class="btn btn-warning">前週</a></th>
                    {% for day in days %}
                        {% if day in public_holidays %}
                            <th style="background-color: yellow">{{ day | date:"d(D)" }}
                        {% elif day.weekday == 5 %}
                            <th style="color: blue;">{{ day | date:"d(D)" }}
                        {% elif day.weekday == 6 %}
                            <th style="color: red;">{{ day | date:"d(D)" }}
                        {% else %}
                            <th>{{ day | date:"d(D)" }}
                        {% endif %}

                        <br><a href="{% url 'app:my_page_day_detail' item.pk day.year day.month day.day %}">詳細</a>
                    {% endfor %}
                    <td><a href="{% url 'app:my_page_calendar' item.pk next.year next.month next.day %}" class="btn btn-warning">次週</a></th>
                </tr>

            <tbody>
                {% for hour, schedules in calendar.items %}
                    <tr style="font-size:12px">
                        <td scope='row'>{{ hour }}:00</td>
                        {% for dt, book in schedules.items %}
                            <td>
                                {% if book %}

                                    {% for s in book %}
                                    <p class="font-weight-bold text-success" style="display:inline;">{{ s.name }}:</p>
                                    <form method="POST" style="display: inline" action="{% url 'app:delete_hour' item.pk dt.year dt.month dt.day hour%}">
                                        {% csrf_token %}
                                        <button class="btn btn-danger" type="submit">削除</button>
                                    </form>
                                    {% endfor %}
                                {% else %}
                                    <i class="far fa-circle text-info"></i>
                                {% endif %}
                            </td>

                        {% endfor %}
                        <td>
                            {{ hour }}:00
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
    </table>

    <form action="{% url 'app:item_del' item.pk %}" method="POST" onSubmit="return disp_item_del()">
        {% csrf_token %}
        <button class="btn btn-warning" type="submit">受付を消去する</button>
    </form>
    <br>
{% endblock %}

app/templates/app/my_page_day_detail.html
{% extends 'app/base.html' %}

{% block content %}

    <h4>{{ item.name }} 受付詳細ページ</h4>
    <p>{{ view.kwargs.year }}年{{ view.kwargs.month }}月{{ view.kwargs.day }}日の予約一覧</p>
    <a href="{% url 'app:my_page_calendar' item.pk %}">スタッフ用カレンダーページへ戻る</a>

    <div class="button mx-auto">
        <table style= "border-collapse: separate; border-spacing: 8px 0px;">
            <tr>
                <td >
                    <form action="{% url 'app:my_page_holiday_add_day' item.pk view.kwargs.year view.kwargs.month view.kwargs.day %}"
                            method="POST" onSubmit="return disp_hol()">
                        {% csrf_token %}
                        <button  class="btn btn-warning" type="submit">予約不可にする(1日)</button>
                    </form>
                </td>
                <td>
                    <form method="POST" action="{% url 'app:delete_day' item.pk view.kwargs.year view.kwargs.month view.kwargs.day%}" onSubmit="return disp_del()">
                        {% csrf_token %}
                        <button class="btn btn-warning" type="submit">削除(1日)</button>
                    </form>
                </td>
            </tr>
        </table>
    </div>

    <br>
    <div class="main_schedule">           
            <table class="table table-bordered table-sm text-center bg-light">
            {% for hour, schedules in calendar.items %}
                <tr style="font-size:12px">
                    <td>
                        {{ hour }}:00
                    </td>
                    <td>
                        {% if schedules %}
                            {% for s in schedules %}
                                {{ s.name }}
                            {% endfor %}
                        {% else %}
                            <form action="{% url 'app:my_page_holiday_add_hour' item.pk view.kwargs.year view.kwargs.month view.kwargs.day hour %}"
                                method="POST">
                                {% csrf_token %}
                                <button class="btn btn-Info" type="submit">予約不可(1時間)</button>
                            </form>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </table>        
    </div>
    
    
{% endblock %}

app/templates/app/myschedule_detail.html
{% extends 'app/base.html' %}

{% block content %}
    <br>
    <a href="{% url 'app:calendar' item.pk %}"> << カレンダーページへ戻る</a>
    <div class="card eveadd-auth my-5 mx-auto">
        <div class="eveadd-body">
            
            <h5 class="card-title text-center">{{ item.name }} 予約キャンセル</h5>
            <div style="font-size: 16px;">
                予約者名 : <p style="font-weight: bold; display: inline;">{{ schedule.name }}</p>
            </div>

            {% if flag %}
                <p style="font-size: 16px;">{{ view.kwargs.year }}年{{ view.kwargs.month }}月{{ view.kwargs.day }}日 {{ view.kwargs.hour }}時から</p>
                <form action = "{% url 'app:myschedule_del' schedule.pk %}" method="POST" class="form-auth">
                    {% csrf_token %}
                    <div class="form-label-group form_wrap form_wrap-2">
                        <input type="number" class='form-control' min="1" max = "72" value="1" name="number" placeholder='時間'><h6><br>時間分をキャンセル</h6> 
                    </div>
                    <div class="form-label-group form_wrap">
                        <table>
                            <tr>
                                <td><h6>暗証番号:</h6></td>
                                <td><input type="text" id="pas" name="pw" maxlength="4" class='form-control' pattern="\d*" oninput="value = value.replace(/[０-９]/g,s => String.fromCharCode(s.charCodeAt(0) - 65248)).replace(/\D/g,'');" placeholder="暗証番号(半角数字4桁)"></td>
                            </tr>
                        </table>                  
                        
                        
                    </div>
                    <br>
                    <div class="button mx-auto">
                        <button class="btn btn-lg btn btn-danger mx-auto" type="submit">これでキャンセルする</button>
                    </div>
                </form>
            {% else %}
                <br>
                <p style="font-size: 16px;"> 暗証番号を入力していないため、予約のキャンセルはできません。 <br>
                    キャンセルしたい場合はサイト管理者に連絡してください。
                </p>
            {% endif %}
        </div>
    </div>
    
    
    
{% endblock %}

app/templates/app/rest.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}

<div class="card card-auth my-5 mx-auto">
    <div class="card-body">
        <h5 class="card-title text-center">{{ item.name }} 休み一括設定フォーム</h5>

        <form action = "{% url 'app:sendrest' item.pk %}" method="POST" class="form-auth">
            {% csrf_token %}
            <input type="date" class="form-control" name= "start" required>
            から
            <input type="date" class="form-control" name= "end" required>
            まで

            <div class="form-label-group">
                <input type="checkbox" value="0" name="weeks" >月　
                <input type="checkbox" value="1" name="weeks" >火　
                <input type="checkbox" value="2" name="weeks" >水　
                <input type="checkbox" value="3" name="weeks" >木　
                <input type="checkbox" value="4" name="weeks" >金　
                <input type="checkbox" value="5" name="weeks" >土　
                <input type="checkbox" value="6" name="weeks" >日　
            </div>
            <br>
            <p class="indent-2">で設定する</p>
            <div class="button mx-auto">
                <button class="btn btn-lg btn-primary btn-block mx-auto" type="submit">送信</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

app/templates/app/schedule_form.html
{% extends 'app/base.html' %}

{% block content %}

    <h1>{{ schedule.item.name }}受付 変更ページ</h1>
    <form action="" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>

    <hr>
    <form action="{% url 'app:my_page_schedule_delete' schedule.pk %}" method="POST">
        {% csrf_token %}
        <button type="submit">削除</button>
    </form>
{% endblock %}

app/templates/app/some_event_add.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div style="text-align: left;">
    <a href="{% url 'app:item' %}" class="btn btn-default"> << カレンダーへ戻る</a>
</div>
<br>
<a href="{% url 'app:event_add' %}" class="btn btn-outline-primary">1つだけ追加したい場合</a>

<div class="card eveadd-auth my-5 mx-auto">
    <div class="eveadd-body">
        <h5 class="card-title text-center">受付複数追加フォーム</h5>
        <form method="post" class="form-auth" enctype="multipart/form-data">
            {% csrf_token %}

            <li type="disc" class="font-weight-bold" style="font-size: 13px; color: rgb(0, 102, 143);">イベント名</li><br>
            <div class="form-label-group">
                {% render_field form.name class='form-control' placeholder='イベント名' %}
            </div>
            <br><br>
            
            <li type="disc" class="font-weight-bold" style="font-size: 13px; color: rgb(0, 102, 143);">追加する期間の指定</li><br>
            <div class="form-label-group">
                <input type="date" class="form-control" name= "start" required>
                <p style="text-align: right;">から</p>
                <input type="date" class="form-control" name= "end" required>
                <p style="text-align: right;">までの範囲</p>
            </div>
            <fieldset>
                <div data-toggle='buttons' id='menu' style="font-size: 16px;">
                    <label class='btn btn-default'>
                        <input type="checkbox" value="0" name="weeks" />月 
                    </label>
                    <label class='btn btn-default'>
                        <input type="checkbox" value="1" name="weeks" />火
                    </label>
                    <label class='btn btn-default'>
                        <input type="checkbox" value="2" name="weeks" />水
                    </label>
                    <label class='btn btn-default'>
                        <input type="checkbox" value="3" name="weeks" />木
                    </label>
                    <label class='btn btn-default'>
                        <input type="checkbox" value="4" name="weeks" />金
                    </label>
                    <label class='btn btn-default'>
                        <input type="checkbox" value="5" name="weeks" />土
                    </label>
                    <label class='btn btn-default'>
                        <input type="checkbox" value="6" name="weeks" />日
                    </label>
                </div>
            </fieldset>  
            <br><br>

            <li type="disc" class="font-weight-bold" style="font-size: 13px; color: rgb(0, 102, 143);">予約期限の指定</li>
            <p>　※開催 [ 1/5 ] 、許可 [ 2日前 ] 、締切 [ 1日前 ]の場合
                <br>　　　　　　→予約期間　[ 1/3　00:00 ] ～ [ 1/4　23:59 ] </p>
            <br>
            <div class="form-label-group">
                {% render_field form.book_start class='form-control' min="0" placeholder='何日前に予約を許可するか' %}
                <p style="text-align: right;">日前に予約を許可</p>
            </div>   
            <div class="form-label-group">
                {% render_field form.book_end class='form-control' min="0" placeholder='何日前に締め切るか' %}
                <p style="text-align: right;">日前に予約を締切</p>
            </div>
            <br><br>

            <li type="disc" class="font-weight-bold" style="font-size: 13px; color: rgb(0, 102, 143);">予約制限人数</li>
            <p>　※未入力の場合は無制限になります</p>
            <div class="form-label-group">
                {% render_field form.limit class='form-control' placeholder='予約制限人数' %}
            </div>
            <br><br>

            <li type="disc" class="font-weight-bold" style="font-size: 13px; color: rgb(0, 102, 143);">備考</li><br>
            <div class="form-label-group">
                {% render_field form.description class='form-control' placeholder='備考 ( 備考は詳細画面で表示されます ) ' %}
            </div>
            <div class="button mx-auto">
                <button class="btn btn-lg btn-primary btn-block mx-auto" type="submit">受付を追加</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}